apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        app: crm
    spec:
      containers:
        - name: crm
          image: my-crm-image:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: crm-service
spec:
  selector:
    app: crm
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
